language: python
python:
- '3.9'
before_install:
- chmod 755 ./python/prebuild.sh
install:
- pip install -r ./python/requirements.txt
script:
- travis_wait "./python/prebuild.sh"
notifications:
  email:
    recipients:
    - davidlowe@nypl.org
    - hello@mauriciogiraldo.com
before_deploy:
- echo 'Cleaning extraneous files before S3 deploy'
- rm -rf ./python/
- rm README.md
- rm LICENSE
- rm ./csv/*.csv
deploy:
  provider: pages:git
  edge: true
  token: $GH_PAGES_TOKEN
  local_dir: ./csv
  on:
    repo: mgiraldo/pic-data
    branch: main
  skip_cleanup: true
