language: python
python:
- '3.9'
before_install:
- chmod 755 ./python/prebuild.sh
install:
- pip install -r ./python/requirements.txt
script:
- travis_wait "./python/prebuild.sh"
notifications:
  email:
    recipients:
    - davidlowe@nypl.org
    - hello@mauriciogiraldo.com
before_deploy:
- echo 'Cleaning extraneous files before S3 deploy'
- rm -rf ./python/
- rm README.md
- rm LICENSE
deploy:
  provider: s3
  edge: true
  cache_control: max-age=0
  access_key_id: AKIAT6VUAOZSIK73VAUA
  secret_access_key: $AWS_SECRET
  bucket: mga-pic-data
  acl: public_read
  on:
    repo: mgiraldo/pic-data
    branch: main
  skip_cleanup: true
