language: python
python:
- '2.7'
before_install:
- chmod 755 ./python/prebuild.sh
install:
- pip install -r ./python/requirements.txt
script:
- travis_wait "./python/prebuild.sh"
notifications:
  email:
    recipients:
    - davidlowe@nypl.org
    - hello@mauriciogiraldo.com
before_deploy:
- echo 'Cleaning extraneous files before S3 deploy'
- rm ./python/*
- rm README.md
- rm LICENSE
- rmdir python
deploy:
  provider: s3
  cache_control: max-age=0
  access_key_id: AKIAT6VUAOZSGQ25FGX4
  secret_access_key:
    secure: AhZDSIkFT5nYXyo+NgaBgslwVOBRbOGWzJBfCYw7lNfQB4otwXkfOyo4iV+t3uU5uoYsbTEwsRbFiqeDbYnz82UzN2qYlNmkCoMZ6Z7A4b3BXUG1rOQpEn47H4yVui19ZYphJDhxLYdYnZmnNGyn7gzhuIHPRDIz8HwAk2YbJx+xe8c5A/xtHXUZ09RWhaVwnilHnrMFmus0c17qJNUXE2NWulGGRuH8I+K71KppI35Auk0Hcto5ckdBjBUH9f6ZDfkO0bCoL/QuWX2ZA3qWd1s/59rLtwl6K3UsvDIklaH0OXeBUiRnbMXmn9htNu4FHNyTK/zv3vhCzzaBMNzksfMH1pMrdDTWbW4qf0g5/R/de0rhN/eLVZXhXwxFuxou+L/WKaLG+XPLVjSjxJG3GdBpbLGpb9TR6ynk6ekQyoD63tOYjj+8IoEhl4Nl8t/JV1K6ySXPMyXJgx4hhjDtJmoDSOegKXTmQMkuF9JmHTlO3+ksU+AToYwbuhQvlDxGRhEOs9teMneWNHybbDyNL06GPnhq0L6dSxs7a1Jda2wrvi8FlLsFAwA8fnkEojflw0hOgPuYrdxWOCpHfbjeD52rdroDjxVmBnkGvtgHDQ1Z9du0ZK1eJEi5Et9uK6zdGo1KG51aT37KYbn2yMEgQnbA4biefDJ0nF2Bhd44Q/4=
  bucket: mga-pic-data
  skip_cleanup: true
  acl: public_read
  on:
    repo: mgiraldo/pic-data
