language: python
python:
- '2.7'
before_install:
- chmod 755 ./python/prebuild.sh
install:
- pip install -r ./python/requirements.txt
script:
- travis_wait "./python/prebuild.sh"
notifications:
  email:
    recipients:
    - davidlowe@nypl.org
    - hello@mauriciogiraldo.com
before_deploy:
- echo 'Cleaning extraneous files before S3 deploy'
- rm ./python/*
- rm README.md
- rm LICENSE
- rmdir python
deploy:
  provider: s3
  edge: true
  cache_control: max-age=0
  access_key_id: AKIAT6VUAOZSGQ25FGX4
  secret_access_key:
    secure: "hqA5UBXQoeWzYDWmX16T53Yjeyu4nPU9bgBC05fJLx1GMwGx/zcdXRYC9wSLctXvdAB6rUddgDMazFEBXqA5jpPkqX70Z9APQs2NWK0dHv8qHVg9LfdeWJCZj6Ue5U4aZU8RX8xoI/3CDlsmwQ5f1y7gOfOEihQp7gDZZBO5JBQ9iD8D6i7iOlUs1fp8H3UOQ1ClTPGrji9QMv6hQ7TETT/ha5x78+RGTUafYHySiSG29i07wV2b84ljOY3vGLaA9cNo52GsouwksycFRK8+pEDImMmjArrfXpPPfomxyoF+oyyQDaIDAmeiI0OgIXWyNL0yzeCUEo+ErZcxKNztMEPln/b8PNccIxszE8d+ZjcD20bJPLCmG8+BfCufmVYcHNl/lnDCHvN55BD3dVZcBsb+NfTHTqlpKLImFrW9KEpIYrL5hk8rEI6QrrO4t9bFICJgqXH6966vEoGjAMP5ntNxfnxBs/krLjTy9f8qx2h/QBKHxbziuhr4Y4xz5FK66byZeotHAjJWLqV7diUJLbKtdX58jD6PFqhnvGcZ/nizl6X4QbZKxhu1yWzqpfbFhx3zORV7lTkDn6wsuZ+wvRcEQvobIMZ1kHPIb79c2DVTHKBWjCgG85eofbA0p3R1oOeh5JFaeuMQQ2lnapNX6XrFM2di2IEOPUHwlqD/kyw="
  bucket: mga-pic-data
  acl: public_read
  on:
    repo: mgiraldo/pic-data
  skip_cleanup: true
