language: python
python:
- '2.7'
before_install:
- chmod 755 ./python/prebuild.sh
install:
- pip install -r ./python/requirements.txt
script:
- travis_wait "./python/prebuild.sh"
notifications:
  email:
    recipients:
    - davidlowe@nypl.org
    - hello@mauriciogiraldo.com
before_deploy:
- echo 'Cleaning extraneous files before S3 deploy'
- rm ./python/*
- rm README.md
- rm LICENSE
- rmdir python
deploy:
  provider: s3
  cache_control: max-age=0
  access_key_id: AKIAT6VUAOZSGQ25FGX4
  secret_access_key:
    secure: lVIq5jBFlIi7sNVZshnWte7Df4wNfH2gqMirjNokVUOa6RF13md89FAnjUQHkqiRZq8UGIOQudd0qfqPeLR1/Zhqj7Q5aa7gfQdD3+DVF1ZSJ59mTMQ83vIcRsqCPyapUr1jLiNifL5c0OyblYvY8Ex8q1h9IM/6I20554vE6qcLGicXePC2JlAootcjFZqc4TGDKecANv5kJsYqp7AeIpUBOq9bH07TUP1vJnoHSlZvg5nqpugJ8841fWQDYqUuOOeVFwe+S969LTUMxgm5sU7XKHytijnuV/1oyA+6taMPf2jYjyYer8+v2FdRYAEhL04pXzgYMiG64tSRycIsTXFbLTTvWVMXFBy/huDXgFWgzMd0ws921Oq1H0OfCyaOoTpGfXwkNezaOTmFwD3F6IlIu+2fkifFrTAr46vNnNaccvrPrL4bk56hcr7T6ng9TkClNc8JGsEvQ+NJmZdzPPj73QKbpQvMM3UFLr8E4YxcPaF6VqJaRx9PYdE91GiHrDL2wHCj9kQy1eSpH5Z51VM/73OKUzTfxmGKuEZ4HynwXX0Vx3+Qd//sA57f9jE8gB9JDkshKpZi/0kcrF/5hO6GdL9TsicnCOYoIfcy1JgFROpsgmCamg3RqEU5nwLkXO4oxkSrbsueViPoqVwquufIAeWsQGEiyXBOoueOKPw=
  bucket: mga-pic-data
  acl: public_read
  on:
    repo: mgiraldo/pic-data
  skip_cleanup: 'true'
