language: python
python:
- '2.7'
before_install:
- chmod 755 ./python/prebuild.sh
install:
- pip install -r ./python/requirements.txt
script:
- "./python/prebuild.sh"
notifications:
  email: false
  slack:
    secure: Q59WrM1w1SFlch23Wl4/B1zK1o5A7VyuR1HTgUQM9cGbDx+OyeJnFcJl3/1gXytyw82hdUmUCayvUeeQnCNLBWXamclUALjkFNDiVf7VdRfvOdNesGLW3oGGjHgDNXBVIQpaBfDBQknKh9Gn8XOzzvJ0efXQBGasE+dJjJz7EeeanHAnLNGEJQL15FUtlewJ7bnD5YMaks6oTD9/R+t85Bf4tqK4gIYYzFjZMRgkNW14gC5PKOPQVdh2TptfWF/0mTP/Rloa8PdanX7SmPXR8vHziqD8dvc2xtSbRqtMYcmM5qlGniOPu90y2OGfdxlqrQdj1q/mNanK0DO5R3d9QQLdRgahjUKtrlazThzKXRCkn1423lWbk/GTQAGBHToJ7IUo3EfMN+U46UO0RVqR4+sPgLLjlHgeqxiZXwj/yoVXClJEu2ik+KTXNJtdXWPqeC0aSAsS0ew1heQWWEpRtsC91K6dh6AWeHGaqumLnOTZN+mR2c/aVB9JOTYG4vdO8KxAbjNt/9yEv2IkDknNlZFSviZOzJSF0vobrhrJfh+b7sr83XXY36EzKX8yrptluDGcNF5tAkBVK9QiYxbCjY2EDeQHLaWTvxRvyxmsMDWEsca4eNt6XE66JzoQstIonei5ETp+0r5RN3dezL5zSj1ESy3+5Srt5H0FHhT6/kY=
before_deploy:
- echo 'Cleaning extraneous files before S3 deploy'
- rm ./python/*
- rm README.md
- rm LICENSE
- rmdir python
deploy:
  provider: s3
  cache_control: "max-age=0"
  access_key_id: AKIAI3GZHKGEODNQACTA
  secret_access_key:
    secure: eiBr7zsdq5MhoHzQIgfwi4BsnaU4wz692C6swSr+B/ywZvwWY2p0k6f9Tm+hqGcXXK6XsdW4weyHk+eYvNof8mgpHkoV5FbJ3g2hTmyExn0QQVk7LJD7A9u+Of/yOkEvn0cAB2QWXVtB+NHc7rwwF8yvJ8JFGq5ZFyamSvV7iqEnQhuG1EG/nqq8OCE4A2gu9y5C3mDlbLAJEdTacHzXEIjDAAb+9BL4Kd2BvwU9V7KaLVhLEG49LbhDnA/BXM55Ho9mEoPj2fgGmzXwloCDBcAMDp6LhkKao8AClqezkQsdnMSY+SitQ+Ndb+aOcQ3VRKQJ8otCnWmeNxQ9+jbk4vnhfKuBbvcFL/bpOwGbtvNBKQeO1cOkNNbqyPRC6cf4E0pFX4NE9R5pqZNrVuBWCY8JgubABd3wcp/JE7n7qBTV36r1i6cWm0u0AymmfBQZjGVVQL6huysezyYmvb8tgdlwHRNM2V+PDH1ZJE4vjaQj49khjlBLCracougM4v6KmTCmUMOYSZ4MDuyd63eOy4PU+vAdw9wZtzx3J+GCyeOtwob1+i8si3gRhgm4LjtVRPsKy2AH/qAeVs8IXPvW5IgdxFYNqNnanOIZ/zSzTk0dB6VQyyvXzK1XQiu9EANvESwLk6iqoENAl8pbnOtvdxyujmqjI7TKMpI4z5GEEW4=
  bucket: pic-data
  skip_cleanup: true
  acl: public_read
  on:
    repo: NYPL/pic-data
