language: python
python:
- '2.7'
before_install:
- chmod 755 ./python/prebuild.sh
install:
- pip install -r ./python/requirements.txt
script:
- "./python/prebuild.sh"
env:
  global:
  - GH_REPO="nypl/pic-app"
  - secure: CIy/aewuNg9sbAS92RxsWEIvgaTr8nyFFQbRkTlXsK7w+HKVPjSQiBd3x8kqkRoL0qM1+gsGQIf5h5yjWwiLqj4mCPDIjG1WOcS7xUgEPBrnjVs5tNNy9KgmabAgSA/PwCoGG+edsVeCxISW7UE86YOam5A9eOGVmVxuu4WxfPVi4KUTAvu/yiLuuDUikVEhVE17eF02PP6tiLU/9ahgHyJ6g3+EA/Imn2zFaF88p2lYXCqmqqPi+q+OS/zRUQWDh/a7TplV7maPUJOd7sQaMzKoGXr8C0LUyO4zmf5oA0xonh+go6Lh+cfPG+Aao3l/cG1FdBBT4ZOWCteqlXhYmkEG9DspSHTtdj1ZdYEl+V7wCpT+RfjWDi8jQbjzjNIYirDPqY8/BY/JlpIRWvXscUdViNZaS8D11mhdrAHWJqzMxoBeRhZV89GXY0XwILodbnRPtCRea7Ob9TiUw1eHrPd4phg7PY7Z6ca4etW2Txli+qT0v85IRsX2vydKYWlFp8ZpxUBoGjbs5RkNZv8qiyNsRuY7JmH+iPZPwjKpl7oJvuwEmDXBI8gihBTwbVW7qvXDuUvvzz764sk2VrUzDLEzCMz3bwL/7MSxbNcJmFccuOa49lBhZOLWXczxGepjbJ5j6u4ufQ/S/wsbRonthycFz2kxFelGAEGUDqQHmuQ=
notifications:
  email: false
  slack:
    secure: idWXWKmV7SchA8SG3F4qVp/Ym/UvcxgU3RE0eGPhAzCM8oxqlj672TjMplNSVcR+nfZ52Ldwr5vJOjGFrJ5j8qrbY7p9EWLPPxQV2YJqXWc+VDCetyKB55DLW01zBY7RQugSsz/UUGlcSwVGWP+dsq9vC4z2JPaZ4xgyHkEPz2f9ve3jcziWbC6dCU5P40FgwWrMquD2iRe+Y+4Sy20RCgIVGgGMB1DGLuWzONI1vZI8zdOSGDM2S3ACTigLfc6eKiF0Z/JITtmVgqLHGRZ51FMiawhKGcW36d3CpNvyE28GMaKGa6CTe4P9u9MuCG/Qs8wlyj2pK15+ywzAc7ek0uBvSZ+/2TdOQKoqWA/Cz8J8SBjwxewp0zwKkNfXF2sg9szl6G1cGOUBjPH9cUp0izDLd8m9gKoWmINe/ynmekCo/UhCPM/nhv9RWMkQTivkdguYBiG+bXNltTc1uDQuJEHg7GefoLeuVRKmM3RQRHpWJs1NMZkwtiLyzcpA5uEJmMbJqrqozmdFtjDvYIJ4K/Fg377PDif2b4KnaDkj4sdb9HB2FaSAPvaAbZ2nJRzFgSKbFFM+JKeywSPpkv8YS7AIn+HPPd24nwHTHy70Q+JnRExsn89wnNz7E7icNXHywXtSFRIsNEgJzpEEBpYu6V6DkE9ibF4Ngc56O8LeRQo=
