language: python
python:
- '2.7'
before_install:
- chmod 755 ./python/prebuild.sh
install:
- pip install -r ./python/requirements.txt
script:
- travis_wait "./python/prebuild.sh"
notifications:
  email:
    recipients:
    - davidlowe@nypl.org
    - hello@mauriciogiraldo.com
before_deploy:
- echo 'Cleaning extraneous files before S3 deploy'
- rm ./python/*
- rm README.md
- rm LICENSE
- rmdir python
deploy:
  provider: s3
  cache_control: max-age=0
  access_key_id: AKIAT6VUAOZSGQ25FGX4
  secret_access_key:
    secure: ZHwf6NfGznyD0U9baZgggzC0doYUFHx54iopFfYD2gDXRSLNKT+kX1gkUrKFnLpB7JD7acn2tMOE3Uyr6xyKkj0m/eisXAq62sfQ/UiD+Gxaq8hkjcs4dBxO+yLZy0KWy4p/dOtLXzsXgIEh5lBqTR18TmUe2L0ItasO0NGnowRBmIolr3TUwg8+CNTplzGEPPSaxItrhfC3S2NVSQ5M05IknXNJERtYdzkBO7h2TmLjFN7nxDZJ2Q7dNw7qUYQK8k2pKdPCJbAOFe5hf6XVOjn+nfbXKOD8Wpkxj3TtTLwSIMZuaFg0UE+97gt7UvjqIPNf4Gv62FiJlHq4cHoLX9tmppYQUk9D2hkvE7h5h+M/9wZQMea2gLHGTSOJ2Sky6Atre+BjeNSwPno/X4px9iQHFu70E4hlCDJQCgaeYs0k9z5VR45uwhwabvKjTKE5pXbJKkAHBsjDMQC1l53lPLzyJhEvxTp4HqUBoUawKAVzVGYCGkGLjt4HlcTlKRrCwBWEi6Qyv8jShbWkTfofS4CNpceLYLHyWnU4tDEhGUGK08fg322zJYQxiAdq5/R6mTovhZqfOPhLpXGOvfbjZEVRf2ZVVp2/QzUIWHKj+OCnKS3oJXPSAIxDyEEIjlhCmnRqmvs30TXLBw564BHvGy3fUleUqhlE6ePsNbHOPOY=
  bucket: mga-pic-data
  skip_cleanup: true
  acl: public_read
  on:
    repo: mgiraldo/pic-data
