language: python
python:
- '2.7'
before_install:
- chmod 755 ./python/prebuild.sh
install:
- pip install -r ./python/requirements.txt
script:
- "./python/prebuild.sh"
env:
  global:
  - GH_REPO="nypl/pic-app"
  - secure: mc034rMBjTE3swPENKXb4BfxmkSG7uSQG79otu49DXffF9Yfci7JVBsC+S0BPRRuNPnsdTYkIeSrdGq7BcrHFX4GOijnrDx5NzR/WDiltjFUp2VPSq9ui3DwT/UmwkuTYpxzJGwa63I1r26H5AsMa7PEEBTxHmEzYF+9+XxOT0XpN9nhbUaWb5LuzhCUwCSJtawdTaIw05nEymarJ47crkfVZiZQdJK6P5ii8CM0AbLZvZSf1ex8KHekzQToON4vNtnNYB0BM/boJRf5D1qiOT5pEGoVPOP3cehTz1Juwu+76r6wIe3ZH3NG3SRdHCnx8PdYl6/Y9v1r0l4+IynT+Cx7AmzUw/Jd1IL/W0G/2HRHfZC43U4paCjlmGw3/6wTWnVFbAqZCe5zYcE9JJu/1fjjzJlokOVLeHi4e/Y9hfOxZmBv3el4b/RfVqL92NasRu7w4r9BdXcggKOnusCJSBwkfe9PuULQ4fijqy8C/psQgvBKI26qNTJ83UynxaMT/GzTMZuxFGcMb138lR0mAUL/8ZdywhpHxwcGEioiRr3cjFmAyxfnd+CCH70ICB49YYkWUZ5qbWGC/qbfwouDpr0lI0LfdQxQzcz5owKarsDJm0v5OIsBaee73tijrJGDTN5yRrdqL0/RcYTjmMnRdNjoQatq0jyjdlTzpzimvoY=
notifications:
  email: false
  slack:
    secure: idWXWKmV7SchA8SG3F4qVp/Ym/UvcxgU3RE0eGPhAzCM8oxqlj672TjMplNSVcR+nfZ52Ldwr5vJOjGFrJ5j8qrbY7p9EWLPPxQV2YJqXWc+VDCetyKB55DLW01zBY7RQugSsz/UUGlcSwVGWP+dsq9vC4z2JPaZ4xgyHkEPz2f9ve3jcziWbC6dCU5P40FgwWrMquD2iRe+Y+4Sy20RCgIVGgGMB1DGLuWzONI1vZI8zdOSGDM2S3ACTigLfc6eKiF0Z/JITtmVgqLHGRZ51FMiawhKGcW36d3CpNvyE28GMaKGa6CTe4P9u9MuCG/Qs8wlyj2pK15+ywzAc7ek0uBvSZ+/2TdOQKoqWA/Cz8J8SBjwxewp0zwKkNfXF2sg9szl6G1cGOUBjPH9cUp0izDLd8m9gKoWmINe/ynmekCo/UhCPM/nhv9RWMkQTivkdguYBiG+bXNltTc1uDQuJEHg7GefoLeuVRKmM3RQRHpWJs1NMZkwtiLyzcpA5uEJmMbJqrqozmdFtjDvYIJ4K/Fg377PDif2b4KnaDkj4sdb9HB2FaSAPvaAbZ2nJRzFgSKbFFM+JKeywSPpkv8YS7AIn+HPPd24nwHTHy70Q+JnRExsn89wnNz7E7icNXHywXtSFRIsNEgJzpEEBpYu6V6DkE9ibF4Ngc56O8LeRQo=
