language: python
python:
- '2.7'
before_install:
- chmod 755 ./python/prebuild.sh
install:
- pip install -r ./python/requirements.txt
script:
- "./python/prebuild.sh"
notifications:
  email: false
  slack:
    secure: idWXWKmV7SchA8SG3F4qVp/Ym/UvcxgU3RE0eGPhAzCM8oxqlj672TjMplNSVcR+nfZ52Ldwr5vJOjGFrJ5j8qrbY7p9EWLPPxQV2YJqXWc+VDCetyKB55DLW01zBY7RQugSsz/UUGlcSwVGWP+dsq9vC4z2JPaZ4xgyHkEPz2f9ve3jcziWbC6dCU5P40FgwWrMquD2iRe+Y+4Sy20RCgIVGgGMB1DGLuWzONI1vZI8zdOSGDM2S3ACTigLfc6eKiF0Z/JITtmVgqLHGRZ51FMiawhKGcW36d3CpNvyE28GMaKGa6CTe4P9u9MuCG/Qs8wlyj2pK15+ywzAc7ek0uBvSZ+/2TdOQKoqWA/Cz8J8SBjwxewp0zwKkNfXF2sg9szl6G1cGOUBjPH9cUp0izDLd8m9gKoWmINe/ynmekCo/UhCPM/nhv9RWMkQTivkdguYBiG+bXNltTc1uDQuJEHg7GefoLeuVRKmM3RQRHpWJs1NMZkwtiLyzcpA5uEJmMbJqrqozmdFtjDvYIJ4K/Fg377PDif2b4KnaDkj4sdb9HB2FaSAPvaAbZ2nJRzFgSKbFFM+JKeywSPpkv8YS7AIn+HPPd24nwHTHy70Q+JnRExsn89wnNz7E7icNXHywXtSFRIsNEgJzpEEBpYu6V6DkE9ibF4Ngc56O8LeRQo=
deploy:
  provider: s3
  access_key_id: AKIAI3GZHKGEODNQACTA
  secret_access_key:
    secure: eiBr7zsdq5MhoHzQIgfwi4BsnaU4wz692C6swSr+B/ywZvwWY2p0k6f9Tm+hqGcXXK6XsdW4weyHk+eYvNof8mgpHkoV5FbJ3g2hTmyExn0QQVk7LJD7A9u+Of/yOkEvn0cAB2QWXVtB+NHc7rwwF8yvJ8JFGq5ZFyamSvV7iqEnQhuG1EG/nqq8OCE4A2gu9y5C3mDlbLAJEdTacHzXEIjDAAb+9BL4Kd2BvwU9V7KaLVhLEG49LbhDnA/BXM55Ho9mEoPj2fgGmzXwloCDBcAMDp6LhkKao8AClqezkQsdnMSY+SitQ+Ndb+aOcQ3VRKQJ8otCnWmeNxQ9+jbk4vnhfKuBbvcFL/bpOwGbtvNBKQeO1cOkNNbqyPRC6cf4E0pFX4NE9R5pqZNrVuBWCY8JgubABd3wcp/JE7n7qBTV36r1i6cWm0u0AymmfBQZjGVVQL6huysezyYmvb8tgdlwHRNM2V+PDH1ZJE4vjaQj49khjlBLCracougM4v6KmTCmUMOYSZ4MDuyd63eOy4PU+vAdw9wZtzx3J+GCyeOtwob1+i8si3gRhgm4LjtVRPsKy2AH/qAeVs8IXPvW5IgdxFYNqNnanOIZ/zSzTk0dB6VQyyvXzK1XQiu9EANvESwLk6iqoENAl8pbnOtvdxyujmqjI7TKMpI4z5GEEW4=
  bucket: pic-data
  skip_cleanup: true
  acl: public_read
  on:
    repo: NYPL/pic-data
